os:
- linux
- osx
language: node_js
node_js: 
- node
- 7
- 6
cache:
  directories:
  - $HOME/.cache/yarn
  - node_modules
sudo: false
matrix:
  fast_finish: true
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.21.3
- export PATH=$HOME/.yarn/bin:$PATH
install:
- travis_retry yarn install
script:
- yarn test
after_success:
- test ${TRAVIS_JOB_NUMBER#*.} == 1 && bash yarn.sh
- test ${TRAVIS_JOB_NUMBER#*.} == 1 && travis_retry yarn global add codeclimate-test-reporter
- test ${TRAVIS_JOB_NUMBER#*.} == 1 && codeclimate-test-reporter < test/coverage/lcov.info
addons:
  code_climate:
    repo_token: c656b95d5435de5200989ba0c5c018d2d6fe54ff1f833dab7c562b2563212c2a
notifications:
  email: false
